#title in header
title: "Develop Guide to the NumericalEFT library"

#main info
#owner
# owner: "I am Adi Sakti Jrs"
email: chenkun0228@gmail.com
info: "Blog on the useful techniques to develop the library"
#description
# desc: ""

#menu
menu:
  Works: /Works
  About: /About

#index/main page max show posts (in number)
max_post: 20

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/numericalEFT

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# index_cover: /developer_tutorial/img/home-
# favicon
favicon: /developer_tutorial_hexo/images/favicon.png
# thumbnail
thumbnail: /developer_tutorial_hexo/images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
